apiVersion: v1
kind: Service
metadata:
  name: card-signal-board-api
  namespace: card-signal-board
  labels:
    app: card-signal-board
spec:
  type: LoadBalancer
  selector:
    app: card-signal-board
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
