apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "card-signal-board.serviceAccountName" . }}
  labels:
    {{- include "card-signal-board.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
